# Generated by Django 3.0.7 on 2020-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerrgistration',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
