# Generated by Django 3.0.7 on 2020-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200831_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerrgistration',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dealerrgistration',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dealerrgistration',
            name='pan',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dealerrgistration',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='adhar',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
