# Generated by Django 3.0.7 on 2020-09-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_name', models.CharField(max_length=50, unique=True)),
                ('dict_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State')),
            ],
        ),
        migrations.CreateModel(
            name='DealerAddress',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=200, unique=True)),
                ('address_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
            ],
        ),
    ]
