# Generated by Django 3.0.7 on 2020-09-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dealeraddress_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealeraddress',
            name='address_state',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
    ]
