# Generated by Django 3.0.7 on 2020-09-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dealeraddress_address_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('ftname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('house', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('id_proof', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('add_proof', models.CharField(max_length=50)),
                ('add_id', models.CharField(max_length=50, unique=True)),
                ('reference', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('cstate', models.CharField(max_length=50)),
                ('cdistrict', models.CharField(max_length=50)),
                ('cylinder', models.CharField(max_length=50)),
                ('connection', models.CharField(max_length=50)),
                ('id_file', models.FileField(upload_to='customer_File/')),
                ('add_file', models.FileField(upload_to='customer_File/')),
                ('photo', models.FileField(upload_to='customer_File/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('ftname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('house', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('id_proof', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('add_proof', models.CharField(max_length=50)),
                ('add_id', models.CharField(max_length=50, unique=True)),
                ('reference', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('agenncy_name', models.CharField(max_length=100, unique=True)),
                ('agency_reg', models.CharField(max_length=50, unique=True)),
                ('agency_add', models.TextField()),
                ('id_file', models.FileField(upload_to='distributor_File/')),
                ('add_file', models.FileField(upload_to='distributor_File/')),
                ('photo', models.FileField(upload_to='distributor_File/')),
                ('agency_file', models.FileField(upload_to='distributor_File/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributorAgency',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_name', models.TextField(max_length=200, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
                ('state', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='dealeraddress',
            name='address_dict',
        ),
        migrations.RemoveField(
            model_name='dealeraddress',
            name='address_state',
        ),
        migrations.DeleteModel(
            name='DealerRgistration',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.DeleteModel(
            name='DealerAddress',
        ),
        migrations.AddField(
            model_name='customer',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DistributorAgency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
    ]
