# Generated by Django 3.0.7 on 2020-09-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200916_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoragency',
            name='distributor',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.Distributor'),
        ),
        migrations.AlterField(
            model_name='distributoragency',
            name='idno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
