# Generated by Django 3.0.7 on 2020-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200919_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributoragency',
            name='distributor',
        ),
        migrations.AddField(
            model_name='distributoragency',
            name='dist_id',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
