# Generated by Django 3.0.7 on 2020-09-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200919_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributoragency',
            name='dist_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.Distributor', unique=True),
        ),
    ]
