# Generated by Django 3.0.7 on 2020-09-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200919_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributoragency',
            name='dist_id',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
