# Generated by Django 3.0.7 on 2020-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200919_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributoragency',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='distributoragency',
            name='district',
        ),
        migrations.RemoveField(
            model_name='distributoragency',
            name='state',
        ),
        migrations.AddField(
            model_name='distributoragency',
            name='district_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='distributoragency',
            name='state_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='distributoragency',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
