# Generated by Django 3.0.7 on 2020-09-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200919_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributoragency',
            old_name='idno',
            new_name='d_id',
        ),
    ]
