# Generated by Django 3.0.7 on 2020-09-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200919_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributoragency',
            name='district_id',
        ),
        migrations.AddField(
            model_name='distributoragency',
            name='dist_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.District'),
        ),
        migrations.AlterField(
            model_name='distributoragency',
            name='state_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
    ]
