# Generated by Django 3.0.7 on 2020-09-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200919_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributoragency',
            old_name='dist_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='distributoragency',
            old_name='state_id',
            new_name='state',
        ),
    ]
