# Generated by Django 3.0.7 on 2020-09-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_pricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('price', models.FloatField()),
                ('paymentid', models.CharField(max_length=50)),
                ('status', models.CharField(default='Failed', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('paymentid', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
            ],
        ),
    ]
