# Generated by Django 3.0.7 on 2020-09-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ordermodel_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Distributor'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Distributor'),
        ),
    ]
