# Generated by Django 3.0.7 on 2020-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201002_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
